### ISSUE TITLE
Possibly add uris to headers?

### ISSUE THREAD

**Issue by nelsonpecora** [clay/amphora#276]
Per @cruzanmo https://www.w3.org/wiki/LinkHeader

**Comment by cruzanmo** [comment]
Thinking about this more, the link header would work well, but it might be safer to give the page (and all components) a private UUID stored in the instance's data, which would be more reliable in case we changed the component's name or the URI, which is unlikely, but possible. This idea came up when discussing tracking as well with @gloddy

**Comment by saml** [comment]
I prefer to add links (including rel="self") in representation/payload.

With Link  or Content-Location header alone, it's difficult to write links of each item in a collection resource.

HTML includes links in representation. Atom includes links in representation. Amphora's representation should just follow existing convention and include links in its json representation.

Oh, links are in URL already. You already know the links. They are in headers...etc.   while good arguments, my preference leans towards including links in representation and following established practices of [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS).  To me, including links in Amphora's representation is one critical step towards better API design.

**Comment by yoshokatana** [comment]
See [this discussion](https://github.com/nymag/amphora/issues/108) for why we don't include URIs in the data returned from api calls.

**Comment by cruzanmo** [comment]
I agree the URI should not be in the data. We could either add the URI to the http link header, or add a new id property to page data that would be unique and, to avoid confusion, different form the URI.

**Comment by saml** [comment]
Links are considered metadata. If implementation of amphora is such that links should be treated as main data, not metadata, I can see resistance in adding links in the body (data).

But at the same time, if it can be added to headers (metadata), I don't see why it's not feasible to be added in body (as metadata). Maybe it's too difficult to add a response processing layer/middleware for GET requests in current amphora code base without much factoring? 
For example, for GET, add metadata like links to body before responding.
