### ISSUE TITLE
New `Buffer` Constructor

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#385]
In newer versions of Node certain implementations of the `Buffer` constructor have been deprecated. 

Packages like `atob` are still using the old `Buffer` implementation and should not be relied on. We need to implement the new constructor appropriately.

This is technically a breaking change to the Amphora API because it requires a user to be on Node v6+, so is this a new major or minor version of Amphora? Should this be included in a larger API change for Amphora?

**Comment by nelsonpecora** [comment]
hmm. api-wise, I'd say minor, but let's include it in the next major version so there's no confusion

**Comment by jonwinton** [comment]
Sounds good 👍

**Comment by jonwinton** [comment]
Complete
