### ISSUE TITLE
Better status code and error message for when a component isn't found

### ISSUE THREAD

**Issue by mheiber** [clay/amphora#399]
## Summary:

When a page can't render because a component isn't found, we should get an error message saying that the page can't render because a component isn't found.

## Steps to reproduce
Add a new component reference to editable_components for a component that doesn't exist
Try to create a page
Result: 404 with no message

## Expected result: better error message like "component <component name> not found". Maybe a 500 would be a better status code.

Thanks for your help!

**Comment by pfeytser** [comment]
This is fixed in cases where the data is 404-ing, but needs to be addressed for render.

**Comment by nelsonpecora** [comment]
@jonwinton this is fixed for rendering by https://github.com/clay/amphora/pull/544 yeah?

**Comment by jonwinton** [comment]
Yeah

**Comment by mheiber** [comment]
@jonwinton  @nelsonpecora this seems to be a different issue.
"Add a new component reference to editable_components for a component that doesn't exist"

If the component does not exist, it cannot specify its error code and message.
