### ISSUE TITLE
FAQ/Documentation Questions

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#410]
The docs for Amphora need to be re-written, so what should be in there? I'd like to get a list of questions that need to be answered in the docs and then that will help determine structure.

Literally ask anything, it all helps. Answers won't be provided on this thread but will be answered in the docs that get written.

**Comment by byronhulcher** [comment]
How can `amphora` be used outside of the `Clay` stack on its own? How could one write their own stack around `amphora`?

**Comment by jonwinton** [comment]
Piggybacking of Byron's question, maybe I can actually get the `Clay` stack documented. Includes plugins for Amphora, tooling, etc.

**Comment by jasondecastro** [comment]
How can I write my own alternative version of `amphora` to plug into the `Clay` stack?

**Comment by jasondecastro** [comment]
Can I use `amphora` with another `NodeJS` framework that's not `Express`?

**Comment by jasondecastro** [comment]
Are there any performance benchmarks for Amphora?

**Comment by jasondecastro** [comment]
How big is Amphora, in terms of file size?

**Comment by gloddy** [comment]
- What is amphora?
- Why would I use it?
- What does it do?
- What doesn't it do?
- What is it similar to?
- Why is it better than choosing x?
- Why redis? Do I have to use redis?

**Comment by mheiber** [comment]
- For each route, what is it for, what is the format of the request and format of the response? For example, creating a USER is a post to /<site>/users with a JSON body, but creating a uri is a PUT to /uris/<base64encoded-slug> with a text/plain string body that is a ref to a page. SwaggerDocs maybe?
- How does the `compose` process work, and what choices to we get to make, and how? For example, it took me a while to figure out what parts of bundling are done in a Clay implementation, which parts are Ampora, and how the two interact.
- What is a "Clay implementation"?
- What are all the settings in config.yml and what do they do?

**Comment by amycheng** [comment]
Wrote some feedback in pink:
[README.MD](https://docs.google.com/a/nymag.com/document/d/1goo3ZtLpzgwDurOigup8dGmHcGb0POc9cfimRbb23v4/edit?usp=sharing)

Other notes:
- Do we have an Amphora logo? We should add that to the README file so it's more welcoming.
- I think it would make more sense to call the routes docs as "Api Routes"

**Comment by pfeytser** [comment]
From the [Trello ticket](https://trello.com/c/5vYi8V4J)

- Data versioning
- Environment variables
- Renderers
- Routes
- Lifecycle (Bootstrap, Plugins, etc.)
- Plugins
- Publishing services
- Database choice
- Additional tooling (Amphora search, Kiln, etc.)
- Best practices? (clustering, isomorphic services)
- Roadmap?

**Comment by nelsonpecora** [comment]
Thanks for your responses, everyone! They've been added to [our documentation push](https://github.com/clay/amphora/issues/489)
