### ISSUE TITLE
Auth url should pass protocol (if available)

### ISSUE THREAD

**Issue by elgreg** [clay/amphora#413]
Currently redirect URLs for auth will always go to http even if your site is on https. 

Behavior
=======

Try logging into a site that runs on https but alwasy redirected back to http://[blah]/auth/google/callback

Expected Behavior
==============

I should be sent back to https://[blah].com/auth/google/callback if I specify a proto in my site config

**Comment by elgreg** [comment]
I think I have this done here: https://github.com/nymag/amphora/compare/master...slategroup:413-allow-proto-in-auth-redirect?expand=1

@jonwinton or @nelsonpecora what's the best place to ask to merge to?

**Comment by jonwinton** [comment]
Sorry, @elgreg! Been distracted with all the things. I'd like to look at getting this integrated this week/next week. I'm going to do some tests with it in our setup and then I'll circle back with you about submitting the PR. 

Again, sorry for the delay! Let's get this in 3.0 for sure :)

**Comment by jonwinton** [comment]
This definitely works because the other PR got merged and released. I can verify because I had to personally add the https route to our google oauth app.
