### ISSUE TITLE
doc: what is a publishing service?

### ISSUE THREAD

**Issue by nelsonpecora** [clay/amphora#417]
We should have documentation about the idea of a "publishing service", and generally the workflow for generating urls and publishing

**Comment by jonwinton** [comment]
Changes to pub service in this PR: https://github.com/clay/amphora/pull/455

**Comment by jonwinton** [comment]
Initial pass: http://clay.github.io/amphora/docs/basics/publishing.html

Assuming it will be supported by Clay narrative docs later. Should be enough for people to get up and running with the API, but new issues/PRs can be opened regarding the contents
