### ISSUE TITLE
Handle errors in publish hook

### ISSUE THREAD

**Issue by mheiber** [clay/amphora#432]
### Steps to Reproduce

- Make an amphora plugin with a `publish method` that throws an error:

```js

amphora({
  ...
  plugins: [
    {publish: () => { throw new Error('yarr') },
    amphoraSearch
  ]
})
```

- Publish an article in Kiln

Result:
-  Kiln turns red and indicates there was a problem publishing

![screen shot 2017-08-30 at 5 36 13 pm](https://user-images.githubusercontent.com/4691093/29896148-d705ceca-8da9-11e7-8dde-f738e7cb12b8.jpg)

- However, the page *is* published, which can be seen by refreshing the page

![screen shot 2017-08-30 at 5 36 23 pm](https://user-images.githubusercontent.com/4691093/29896150-d924e308-8da9-11e7-99ee-90be8cd617c2.jpg)

### Suggested mitigation

- Wrap hook plug-in methods in promises.
- If the promise returned by a `publish` method is rejected:
    - Log it to the server console
    - Either show green "Published" indicator anyway, or show a yellow one with an <!> and something indicating what failed.

cc @nelsonpecora for Clay side, @jonwinton for Amphora side

**Comment by nelsonpecora** [comment]
Since these plugin hooks run _after_ a successful publish, I'd catch the error, log it, then proceed normally (returning 200 to the publish call and displaying the green Published message)
