### ISSUE TITLE
Node 8 Support

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#438]
Validate Node 8 support

- What will break?

**Comment by nelsonpecora** [comment]
In my tests with node 8, it doesn't look like there are any obvious breaking things with our setup

**Comment by jonwinton** [comment]
Found one issue with exhausting memory during internal bootstrapping large Clay instances and brought in `highland` to help with memory issues in this PR: https://github.com/clay/amphora/pull/446

Feature branch is working as of `4.2.0` and should be good 👍
