### ISSUE TITLE
Proposal: No Cache Flag

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#440]
Two big complaints around local dev: 

- Caching
- Slow start Time

**Proposal:** Flag passed into Amphora to not memoize
**Secondary Proposal:** Secondary flag to skip bootstrapping (this is the longest startup process and increases in duration with number of bootstrap files)

**Comment by nelsonpecora** [comment]
yes please, on both counts (though memoization and bootstrapping should be on by default)

**Comment by jonwinton** [comment]
Ok cool, going to close this and open two separate issues for this so that they can be done separately
