### ISSUE TITLE
Enable excluding components via query parameter

### ISSUE THREAD

**Issue by mheiber** [clay/amphora#452]
Enable users and machines to exclude components using query parameters.

For example, we could use the following search string to exclude all `block-quote`s and a
single instance of `clay-paragraph`:  `?_exclude=/block-quote/&_exclude=/clay-paragraph/instances/cj8nij4010000ys1u6yz6e48x`.

**Comment by elgreg** [comment]
I am super excited about this for our performance testing. 🎉

**Comment by jonwinton** [comment]
Recommended moving this feature into amphora-html by instituting request hooks. This could then be accomplished without modifying core and different implementations can add their own query params based on their needs.
