### ISSUE TITLE
upgrade.js doesn't run, must be called "upgrade"

### ISSUE THREAD

**Issue by mheiber** [clay/amphora#454]
# Steps to reproduce

1. Make a file called `upgrade.js` that exports an upgrade function and add a version to the schema for that component. [Reference](http://clay.github.io/amphora/docs/upgrade.html#upgradejs-file).
1. Do a GET to the instance.
1. No upgrade happens. If the log level is set to `debug` then you will see `Upgrade tried to run, but no upgrade function was found for ${componentName}`

# Workaround

Make a directory called `upgrade` and put an `index.js` in it. It will run.

# Suggested fix

Option A) Update docs to reflect existing behavior
Option B) Allow both `upgrade.js` (documented behavior) and `upgrade` (actual behavior) by changing this line of code: current `master`: https://github.com/clay/amphora/blob/8f85f740f1249ef155756d247551b5fca749991f/lib/services/upgrade.js
@jonwinton thanks for doing this upgrade stuff

**Comment by jonwinton** [comment]
@mheiber we have a few components that are all working as expected with just an `upgrade.js` file. What Amphora version are you using?

**Comment by mheiber** [comment]
Thanks for taking a look, I tested with 4.2.1
I can post later today with a branch that reproduces the problem. Or, alternatively, find out I mis-spelled something and that there is no bug, which is probably more likely.

**Comment by mheiber** [comment]
yep, I'm still seeing the issue. But I can't figure out what in the code would cause it, since `tryRequire` seems like it would be able to figure out how to resolve `upgrade` to `upgrade.js`.
 I'll Slack you the private branch.

**Comment by mheiber** [comment]
I spelled "upgrade" wrong!!!
Sorry for the trouble
