### ISSUE TITLE
Allow for adding headers to a response in an amphora plugin

### ISSUE THREAD

**Issue by elgreg** [clay/amphora#456]
I'd like to be able to attach a list of all the _refs that are on a page (e.g. the article refs for each story card in the home page) as [surrogate keys with fastly](https://docs.fastly.com/guides/purging/getting-started-with-surrogate-keys). @jonwinton suggested adding the ability to add plugins to rendering in amphora. I'd like to hook into the rendering of the homepage in amphora and add surrogate keys for all URLS of linked articles with a `Surrogate-Key:` header on the HTTP response

**Comment by TTaitFoster** [comment]
Why not just an express middleware?

**Comment by elgreg** [comment]
I would prefer that I had access to the components themselves.  So maybe this belongs in the renderer?

**Comment by jonwinton** [comment]
Yes, completely agree. We'll move to amphora-html.

**Comment by jonwinton** [comment]
Issue moved to [clay/amphora-html #57](https://github.com/clay/amphora-html/issues/57) via [**ZenHub**](https://www.zenhub.com/)
