### ISSUE TITLE
Feature Request: Disable Memoization Runtime Flag

### ISSUE THREAD

**Issue by cperryk** [clay/amphora#458]
So we don't have to restart the server every time a developer edits an asset.

**Comment by jonwinton** [comment]
The scope of hot reloading may be too great for a first pass at the initial issue raised. The better solution might just be to disable memoization based on a runtime flag passed to Amphora. This would mean that changes to files would be respected, but "hot reloading" normally refers to maintaining the state of an application across reloads. Amphora is stateless in this regard, it just needs to not cache file reads.

**Comment by jonwinton** [comment]
# Acceptance Criteria

- [ ] Memoization is enabled by default
- [ ] 100% test coverage maintained
- [ ] Documentation is updated for runtime arguments

**Comment by cperryk** [comment]
@jonwinton Are you imagining Amphora would check `process.argv` itself or instead support an option in setup?

**Comment by jonwinton** [comment]
Setup option.
