### ISSUE TITLE
Breaking Change: DB Keys Prefixed With Site Slugs

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#459]
# Summary

Rather than having keys in the DB correspond directly to a site's `host` + `path`, prefix every key with the site's slug.

**The Kicker**
Don't change the API for users/developers. This means translating the inputs/outputs of Amphora to swap in/out the site slug and the old prefix.

## Routes
- [ ] `/_auth`
- [x] `/_schedule`
  * [x] GET `/`
  * [x] GET `/:name`
  * [x] POST `/`
  * [x] DELETE `/:name`
- [x] `/_pages`
  * [x] GET `/`
  * [x] GET `/@published`
  * [x] GET `/:name`
  * [x] GET `/:name.json`
  * [x] GET `/:name@published`
  * [x] GET `/:name@published.json`
  * [x] GET `/:name.:ext`
  * [x] PUT `/:name@:version`
  * [x] POST `/`
  * [x] PUT `/:name`
  * [x] PUT `/:name@published`
    * [x] Empty Object
    * [x] Page Data
  * [x] PUT `/:name@:version`
  * [x] DELETE `/:name`
  * [x] DELETE `/:name@:version`
- [x] `/_components`
  * [x] GET `/`
  * [x] GET `/:name`
  * [x] GET `/:name/instances`
  * [x] GET `/:name/instances/@published`
  * [x] GET `/:name/instances/:id`
  * [x] GET `/:name/instances/:id.json`
  * [x] GET `/:name/instances/:id.ext`
  * [x] GET `/:name/instances/:id@published`
  * [x] GET `/:name/instances/:id@published.:ext`
  * [x] GET `/:name/instances/:id@:version`
  * [x] GET `/:name/instances/:id@:version.:ext`
  * [x] GET `/:name/schema`
  * [x] PUT `/:name`
  * [x] PUT `/:name/instances/:id`
  * [x] PUT `/:name/instances/:id.json`
  * [x] PUT `/:name/instances/:id@published`
    * [x] Empty Object
    * [x] Page Data
  * [x] PUT `/:name/instances/:id@:version`
  * [x] DELETE `/:name`
  * [x] DELETE `/:name/instances/:id`
  * [x] DELETE `/:name/instances/:id@published`
  * [x] DELETE `/:name/instances/:id@:version`
- [x] `/_lists`
  * [x] GET `/`
  * [x] GET `/:name`
  * [x] PUT `/:name`
- [x] `/_uris`
  * [x] GET `/`
  * [x] GET `/:name`
  * [x] PUT `/:name`
  * [x] DELETE `/:name`
- [x] `/_users`
  * [x] GET `/`
  * [x] GET `/:name`
  * [x] POST `/`
  * [x] PUT `/:name`
  * [x] DELETE `/:name`

## Other Features
- [x] Upgrades
- [ ] Plugins
- [ ] Notifications
- [ ] Publish service internal redirects

## Questions (more will be added in comments as they come up)
1. _Should Amphora expose functions which transform uris in both directions to help with translation?_
  Initially I want to add this feature to a utility package that any project can import and then pull THAT pack into Amphora for the translation

**Comment by jonwinton** [comment]
Work is proceeding on `five-prefix-keys` branch.

**Comment by pfeytser** [comment]
`/_auth`?

**Comment by jonwinton** [comment]
Not handling now
