### ISSUE TITLE
Async/Await Re-Architecture

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#462]
Using async/await is cool, but error handling is an issue. Error handling needs to be handled in a more consistent way in Amphora anyways, but it should take into account new technologies when re-evaluating. 

This deserves some thought and a more adoption of async/await by the general community might reveal some good patterns. Right now I find this article to be interesting: http://blog.grossman.io/how-to-write-async-await-without-try-catch-blocks-in-javascript/

**Comment by pfeytser** [comment]
Just use promises, actually use streams.
