### ISSUE TITLE
Publish history

### ISSUE THREAD

**Issue by pfeytser** [clay/amphora#464]
Actions:
- publish
- unpublish
- schedule
- unschedule
 - archive
- unarchive
- created
- add contributor
 - joined/made first edit

Notes
- apikey->"robots"
- added server-side
- items look like:
{action, timestamp, user}

![history](https://user-images.githubusercontent.com/10674066/33571066-dbc9d7a0-d8fc-11e7-8729-d2892d7e14b8.png)

**Comment by jonwinton** [comment]
Issue moved to [clay/amphora-search #41](https://github.com/clay/amphora-search/issues/41) via [**ZenHub**](https://www.zenhub.com/)
