### ISSUE TITLE
Archive pages

### ISSUE THREAD

**Issue by pfeytser** [clay/amphora#465]

**Comment by nelsonpecora** [comment]
Per discussion:

Pages in the `pages` index should have an `archived` property (boolean), which we can filter by when searching. This should be able to be set from the client via the call to update pages.

**Comment by nelsonpecora** [comment]
Issue moved to [clay/amphora-search #40](https://github.com/clay/amphora-search/issues/40) via [**ZenHub**](https://www.zenhub.com/)
