### ISSUE TITLE
Sorting Sites in Clay Menu

### ISSUE THREAD

**Issue by pfeytser** [clay/amphora#467]
* Break sites into two groups, sites that have been updated within 100 days and sites that have not.
* Each group of sites is ordered alphabetically.
* Group that has not been edited within 100 days appears last and has "faded out" effect. 

Idea: in the site configs, we have a type property. Types are:

main (default) - the main sites/brands, show up on the left of the site select dropdown
secondary - ancillary sites/brands, like popups. show up on the right side of the site select dropdown
archived - archived sites are not searched by default in the clay menu, but may be toggled with a single checkbox (at the bottom of the site select dropdown)
Note: This would mean that users couldn't search a single archived site, but I think that's a good tradeoff.

[Trello ticket](https://trello.com/c/ro3M0Yyx)

**Comment by jonwinton** [comment]
Issue moved to [clay/amphora-search #42](https://github.com/clay/amphora-search/issues/42) via [**ZenHub**](https://www.zenhub.com/)
