### ISSUE TITLE
Amphora Sitemaps

### ISSUE THREAD

**Issue by pfeytser** [clay/amphora#468]
We need to put a platform solution to sitemaps.

- Use an Elastic index for all published content
- Generate the sitemap

Docs:

- News Sitemaps Spec: https://support.google.com/webmasters/answer/74288?hl=en&ref_topic=6080646
- Structured Data in Sitemaps: https://developers.google.com/custom-search/docs/structured_data#addtositemap

**Comment by jonwinton** [comment]
Issue moved to [clay/amphora-search #50](https://github.com/clay/amphora-search/issues/50) via [**ZenHub**](https://www.zenhub.com/)
