### ISSUE TITLE
Amphora FS

### ISSUE THREAD

**Issue by pfeytser** [clay/amphora#469]
Take the `files` module in Amphora and turn it into a standalone package.

Then integrate it into Amphora, Amphora HTML and Amphora Search

**Comment by nelsonpecora** [comment]
Amphora `files` service exports that need to be moved to `amphora-fs`:

* [ ] `getYaml`
* [ ] `getFiles`
* [ ] `getFolders`
* [x] `fileExists`
* [x] `getComponents`
* [x] `getComponentPath`
* [ ] `getComponentModule`
* [ ] `getComponentPackage`
* [ ] `isDirectory`
* [ ] `tryRequire`
* [ ] `readFilePromise`

**Comment by nelsonpecora** [comment]
https://github.com/clay/amphora-fs/releases/tag/v1.0.0
