### ISSUE TITLE
Make `scheme` (protocol) a required site config field

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#485]
The scheme of a site plays a large role in infrastructure and scripting around Clay. To make the scheme of a site more consistent I believe we should make it a core property of the site's `config.yml` file.

Questions/Side Effects:
- Add it to amphora-search's sites mapping
- Assume `https` or `http` if not provided? Or just exit?

Benefits: 
- Easier scripting when the value of the scheme can be grabbed from the `/_sites` endpoint of any host
- Easier to write implementation services when there's a core property on the site config

**Comment by nelsonpecora** [comment]
Two cents: call it protocol, like the rest of clay (and the web) does, and fall back to http (like the web sites). Then it's just a minor feature in amphora 👍🏼

**Comment by jonwinton** [comment]
👍  I'd be down for that.

**Comment by jonwinton** [comment]
Issue came up in #517, closing this proposal since it's now necessary.
