### ISSUE TITLE
set _variation when component renders

### ISSUE THREAD

**Issue by nelsonpecora** [clay/amphora#514]
If a component doesn't have a `_variation` set in the data, set it to the component's name

**Comment by jonwinton** [comment]
What is this data for? If it's relating to the display of the component, does it need to be a part of Amphora or can all this logic live in Amphora HTML?

**Comment by nelsonpecora** [comment]
This should actually be set in amphora-html on render, rather than saved to the db.

Note: `_variation` should only be set if it isn't already in the component data (as users will be able to select different variations via https://app.zenhub.com/workspace/o/clay/clay-kiln/issues/1121)

Note: By default, it should be the component's name, usable as a class identifier.

**Comment by jonwinton** [comment]
Closing

**Comment by nelsonpecora** [comment]
Why was this closed? Was a corresponding amphora-html ticket opened? (if so, please add a link to it)

**Comment by amycheng** [comment]
closed in favor of https://github.com/clay/amphora-html/issues/31
