### ISSUE TITLE
Rendering Logic Refactor (Breaking Change)

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#521]
# Problem
Most of the logic inside of this function is done to ensure that HTML can be rendered specifically for Kiln: https://github.com/clay/amphora/blob/master/lib/render.js#L102 It also means that rendering cannot be separated into a separate process entirely without duplicating the logic in an entirely separate place.

# Proposal
- Move component list and `state` object formation entirely to Amphora HTML
- Env vars should be given to Amphora HTML, not Amphora
- `locals` formation logic should be moved into a package that can be used in a renderer or core Amphora
- The sites service should be consolidated into some package that amphora and a renderer could use. It should be reliant on the filesystem having the site configs available for each process.

**Comment by nelsonpecora** [comment]
What's the status on this?

**Comment by jonwinton** [comment]
Oh, I did this. Closing
