### ISSUE TITLE
Feature Request: Ability to safely delete a component

### ISSUE THREAD

**Issue by byronhulcher** [clay/amphora#525]
I'd like to be able to delete a component from a Clay app that I have no more use for.  Right now, we don't have the ability to confidently delete a component from a clay app, as any page or component whose data would contain an instance deleted component would throw an error.  

Right now, our current approach has been creating multiple `upgrade.js` files in each component that references the to-be-deleted component to swap them.  However, we cannot guarantee that this would handle ALL instances where the to-be-deleted component is referenced, since it could be included wherever through both Kiln and through manual data manipulation.  Additionally, this relies on parent pages/components to receive GET requests. I believe requiring an external tool to GET/`touch` every page/component across a site to force this upgrade would be burdensome and would require:
1) pull request for the upgrade
2) someone runs a bulk GET/`touch` command
3) pull request to remove the component.

I'd like to be able to do this in a single pull request. Ideally, I would be able to delete a component, and configure something in my application so that our composer would automatically either remove instances of the deleted component or migrate to a new instance of a different component, possibly with some sort of mapping function. I've discussed this briefly with @nelsonpecora but welcome input from everyone else!

**Comment by nelsonpecora** [comment]
One idea we discussed:

There are three parts intrinsic to deleting components, and all of them would have to be solved by whatever implementation we design:

* references to the deleted component (in parent components)
* data for the deleted component (which might have to be munged to fit into the _new_ component)
* files for the deleted component (which should be removed from the repo)

One option that Amy came up with would be to have a central registry of deprecated components, e.g. `components/upgrade.js`. This could be checked by amphora's composer, and redirect to new components without having to run a manual upgrade/batch thing. It might look like:

```javascript
module.exports = {
  'old-component': 'new-component', // straight redirect
  'old-component2': (uri, data, locals) => {
    // do data munging to fit the old component's data into the new component's schema
    return { name: 'new-component-2', data: mungedData };
  }
};
```

The basic idea is that amphora would:

1. check the registry and see that the component has been changed
2. check if a new component with the same instance ID as the old component exists (returning it if so), and if not...
3. run the data through any logic necessary
4. create a new instance of the _new component_ with the same instance ID as the old one (note: possible naming collision, but not likely. we should discuss)
5. change the reference in the parent component (which it knows about if this is done when composing, _before_ the fetch of the child component. note: this wouldn't happen if GETting the component directly)
5. delete the old component's instance

This would allow us to upgrade and deprecate whole components with a similar set of assumptions as our component-specific `upgrade.js` workflow. Namely, components would be upgraded at the time they're fetched, allowing us to not worry about the long-tail of possibly-referenced instances from parents we don't know about.

Problems:

* instance IDs might collide (especially when deprecading component where we've hand-written instances into bootstraps)
* instances of the old component might be referenced from multiple places, which we'd have to keep in mind. This is why the registry checks to see if it's "already been converted", allowing us to simply update the parent's reference.
* if the component data is old, we'd normally run it through the component's `upgrade.js` before we could assume it matches the expected latest data structure. this presents a problem with removing the component's files / folder, as we'd probably want to run the data through the component's `upgrade.js` _before_ munging it and sending it to a new component

**Comment by byronhulcher** [comment]
Vulture/Homepage team is very interested in this for vulture pages, they want to rename the `cut-layout` component to something more generic so they can use it for Vulture, I think for section pages?

**Comment by nelsonpecora** [comment]
After some discussion about the problems above, I think the first two aren't issues (same-instance components _should_ expect to use the already-existing instance of the new component, e.g. `instances/new`). The third problem is hard to solve, though. We definitely want to be able to delete the component's folder when sunsetting it, which means we probably have to move the versioning/upgrade logic to some centralized place and reference it in `components/upgrade.js`

**Comment by byronhulcher** [comment]
I like the idea of an `/upgrades/` directory or similar that would have sub-directories of components.  Would we need to reference these at all though? Couldn't amphora look in this directory for `/upgrades/foo/index.js` the same way it looks for `/components/foo/upgrade.js`?  Many of our components already have an `upgrades` folder anyway with individual files for each upgrade so this would be pretty straightforward (but would be a breaking change)

**Comment by nelsonpecora** [comment]
I like keeping the `upgrade.js` stuff for individual components in their folders (since they frequently refer to the `model.js` or do similar things, and because our codebase is delineated by components/feature rather than MVC), but they'd need to be moved to some consolidated place after a component is sunsetted, so maybe we need to call this feature `sunsetting` rather than `upgrading` to differentiate it.

So,

```
sunsetting/
  index.js with map of old-to-new component names
  component-name/ folders with...
    index.js munging script (module.exports = (uri, data, locals) => {}) that can `require` other files in this folder, including old upgrade scripts that are cut+pasted from the old component's folder
```

**Comment by byronhulcher** [comment]
- mapping should support just deleting a component
- mapping will only migrate from component A@latest to component B@latest AT THAT TIME, if previous versions are added after migrration, sunsetting should know to use older version and go through upgrade process
- explore options to streamline current 3 step approach

**Comment by cperryk** [comment]
I wouldn't consider a component truly dead until the code base would look like it does if the component never existed. If that's the goal, this approach would still require two PRs:

1. Add sunsetting logic, move upgrades, and delete the component.
2. After Amphora has deleted all the instances of the component, remove the sunsetting logic and upgrades.

Considering this, I think it would be easier to learn, teach, and do sunsetting if we simply declare the logic within the component code itself and remove the component folder later. Something like this:

```
// componentA/upgrade.js
module.upgrade.sunset = (ref, data, locals) => {
    return {
        component: 'componentB',
        data: {
            // data to be saved to new component
        }
    }
}
```

When we see that the instances are all gone, _then_ we delete the folder, and, in doing so, the component's own sunsetting logic. And then the component is truly and fully deceased. 👼  

The only benefit of a special `sunsets` module or dir is the ability to delete the component folder earlier; we need to come back to collect the garbage either way. IMO, it's not worth the extra file complexity, the manual work of relocating upgrade files, or the risk of people forgetting that.

Keep in mind also that upgrades are actually a lot of code. Some of them (I count at least four cases in the NYM code) actually call their own component's save function.

**Comment by nelsonpecora** [comment]
@cperryk that's an interesting idea!

I'm looking through some prior art, and here's some notes:

* most (older) frameworks like Drupal don't handle this well, if at all
* Ember uses [lifecycle hooks](https://ember-cli.com/extending/#indexjs) in the components themselves (similar to @cperryk's idea)
* Angular has a [long, contentious open issue](https://github.com/angular/angular-cli/issues/900) about doing this in a manual cli script
