### ISSUE TITLE
Proposal: Add query layer and deduplication scopes

### ISSUE THREAD

**Issue by cperryk** [clay/amphora#527]
This proposal adds an Elastic query layer to Amphora. Summary:

* Some components can export a `query` function that returns/resolves an Elastic query object
* Rendering runs all query functions and passes the results into each corresponding component's render function at a fixed key
* On a page, components w/ query functions can be grouped into scopes. When components share a scope, their queries are executed synchronously, and the results of each are excluded from subsequent queries.

See [this gist](https://gist.github.com/jonwinton/368f5502fd9753f5fa090bc7e320f17e) for more detail.

**Comment by pfeytser** [comment]
The focus of this is too narrow, will address in broader discussion.
