### ISSUE TITLE
Consolidate plugin hooks

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#535]
There are two hooks: `publish` and `publishPage`.

The only difference is that `publishPage` has the user who triggered the publish in the payload.

**Comment by jonwinton** [comment]
Right now `publishPage` does not send through all the ops, but maybe plugin listeners should be responsible for getting the data it needs from the page.

**Comment by jonwinton** [comment]
And `unpublish`/`unpublishPage`...

```
// Call the unpublish hook for plugins
      plugins.executeHook('unpublish', {
        url: pageUrl,
        uri: oldData
      });

      plugins.executeHook('unpublishPage', { uri: oldData, url: pageUrl, user: user });
```

**Comment by jonwinton** [comment]
I think we can drop the original plugin hooks and just go with all `*Page` hooks. It'll require some changes in Amphora Search and handlers and would be a breaking change, but it could also make handlers much easier to rationalize about.

**Comment by nelsonpecora** [comment]
Agreed. This also dovetails into the layout editing stuff, since it needs at least one new hook (`publishLayout`)

**Comment by nelsonpecora** [comment]
can this be closed?
