### ISSUE TITLE
Site Routes Update/Issues

### ISSUE THREAD

**Issue by jonwinton** [clay/amphora#541]
## Problem

The current method for attaching routes to a site looks like this:

```javascript
module.exports = function (router, composer, site) {
  const blogPath = '/blog';
  
  // Homepage
  router.get('/', composer);
  // Section pages
  router.get('/:name', composer);
  
  // Blog page
  router.get(blogPath + '/', composer);
  router.get(blogPath, function (req,res) {
    res.redirect(301, site.path + blogPath + '/');
  });
  // Article pages
  router.get('/article/:name', composer);
  router.get('/:year/:month/:name', composer);
  // Author pages
  router.get('/author/:author', composer);
  // Tag pages, but they live at `/news` (for now?)
  router.get('/news/*', composer);
  // Private pages, that won't be publicly seen
  router.get('/_private/:name', composer);

  return router;
};
```

The problem is twofold, in my opinion:

1. You're given all the control in the world to attach routes and modify the resolver, but at the risk of breaking things internal to Clay. Because you have all the control you also have all the responsibility to setup redirects and things you need. It's just a lot of stuff you need to think about as a dev.
2. It takes a lot to build in additional functionality into routing from a platform perspective because Amphora doesn't control attachment of routes to the router.

## Dynamic Routes

Things like author pages and tag pages present an interesting problem in Clay because there are 3(ish) layers to resolving a page's data/html:

`(1) Express Route ---> (2) /_uri/ ---> (3) page uri ---> (4) data/html`

(1) The Express Route is a one-to-many relationship with the _uris of a site
(2) A _uri is a one to one relationship with a page/other _uri
(3) A page is....well it's a one-to-many components, but then those components could be dynamic and use data from the Express Route and it honestly depends on the implementation.
(4) Literally who knows, components can be anything.

What there seems to be a strong use case for is getting around the second item, `_uris`. If we can specify from route level that all requests should go to ONE page that knows how to handle data based off the params defined on the Express Route, then it would be very simple to build dynamic pages in Clay.

### Quick Case For Dynamic Routes

Grubstreet.com has +250k unique tags alone. Given current architecture models for Clay that's a large number of entries in the DB that don't need to be there.

## Solution

Follow patterns by different open-source routers, like [Vue Router](https://router.vuejs.org/en/essentials/dynamic-matching.html). An example conversion of the above code snippet would be:

```javascript
module.exports.routes = [
  { path: '/'},
  { path: '/:name'},
  { path: '/blog/'},
  { path: '/blog', redirect: '/blog/'},
  { path: '/:year/:month/:name' },
  { path: '/author/:author' },
  { path: '/news/:tag', dynamicPage: 'someUniquePageId'},
  { path: '/_private/:name' }
];
```

This would accomplish the following:

1. Make building new features into routing easier because attachment is handled by Amphora
2. Site routes would be more predictable (devs can't attach a POST to a router at this level, leave that for plugins)
3. Make routing an easier concept to learn in Clay.

## Estimate of Time To Complete

Would just need to update/write tests for this: https://github.com/clay/amphora/compare/new-routing?expand=1

**Comment by nelsonpecora** [comment]
Hmm! I like this a lot better than the current approach. Does this mean that there are still `_uris`, but that this config can sort of...override(?) them when you specify a dynamic page? How does the dynamic page stuff connect with the route params? (e.g. what's the difference between `{ path: '/blog/:title' }` and `{ path: '/blog/:title', dynamicPage: 'blogpostID' }`? Or rather, how is the value of the `dynamicPage` prop used?)

**Comment by jonwinton** [comment]
`dynamicPage`  basically just says:

> Skip trying to match this canonical url to a `_uris` companion, I know which page uri you're going to already.

The value of `dynamicPage` is
