### ISSUE TITLE
New Lists API

### ISSUE THREAD

**Issue by nelsonpecora** [clay/amphora#552]
* GET/PUT/DELETE `/_lists/:name`
* GET/PUT/DELETE `/_lists/:name/:item`

* `:item` must be a `cuid`-generated ID
* GET `/_lists/:name` must return an object where each property is denoted by `:item`. Each item must by an object with a `text` property, but may contain other properties (such as `id` for page templates and components, or `count` for tags and authors)
* when fetching and parsing lists, Kiln will decide how to sort them
* we need to establish a migration path for our current lists (manual update script using `claycli`? automatic update in amphora?)

**Comment by nelsonpecora** [comment]
Putting this in discussion so we can figure out a migration path

**Comment by jonwinton** [comment]
What are the required properties for a list item? Can anything else be added that isn't one of these properties?

**Comment by nelsonpecora** [comment]
Ah, I think we need to discuss that bit.

**Comment by jonwinton** [comment]
Not implementing for now
