### ISSUE TITLE
Redirects should take into account the current site

### ISSUE THREAD

**Issue by PedroAlbR** [clay/amphora#557]
Given this route for selectall `{ path: '/smarthome', redirect: '/smarthome/'}`, you would expect to be redirected from `nymag.com/selectall/smarthome` to `nymag.com/selectall/smarthome/` but instead it goes to `nymag.com/smarthome/`. This is because there is no way to get the current site you are in and add it to the redirect, forcing you to write the route like this `{ path: '/smarthome', redirect: '/selectall/smarthome/'}`.

**Comment by nelsonpecora** [comment]
Hmm! That's not good. They should definitely be prefixed with the site domain _and path_
