### ISSUE TITLE
Amphora Entity Handling

### ISSUE THREAD

**Issue by nelsonpecora** [clay/amphora#602]
When saving and rendering components in amphora, `entity` data that the component references must be saved separately to / merged in from the entity's data store.

**On Save (after model.save)**

* the entity should be looked up via a combination of the `entity` name and the `entityKey` value
* fields with `synched` data should be separated from the component's data and saved to the entity
* fields _without_ `synched` data should be saved to the component

**On Render (before model.render)**

* the entity should be looked up via a combination of the `entity` name and the `entityKey` value
* `synched` fields should be merged in from the entity data

**Comment by jonwinton** [comment]
Closing because implementation will change once a few more Kiln/Amphora features are completed.
