### ISSUE TITLE
Fix rendering 404 bug

### ISSUE THREAD

**Issue by elgreg** [clay/amphora#617]
@jonwinton and I discussed this issue over Slack. He can fill you in if you are curious!

Please backport to v6 (we were going to go to v6.9.0 on Slate today, but can go to 6.9.1 or 6.10.0 instead)

**Comment by elgreg** [comment]
Hey! Ran into this again today and would love to see it resolved - went down quite the 🐰 🕳️ .

**Comment by phyllisstein** [comment]
Hi @elgreg ! Thanks for the nudge here. We’ve got a fix in `master` that we can release. Are you still running an older version? Or would a new `8.x` work for you?

**Comment by phyllisstein** [comment]
Released as `v8.2.0`. Keeping this open in case you need the fix in an earlier version.

**Comment by elgreg** [comment]
We're on the latest so should be able to upgrade to this. Thanks!

**Comment by phyllisstein** [comment]
No worries! Let me know if you need us to take another look.
